# This file is *NOT* reloaded automatically when you use 'bundle exec jekyll
# serve'. If you change this file, please restart the server process.

# Site Variables
# These can be accessed such {{ site.foo }}. The site must restarted for these to be
# reloaded.
# Title is also the owner's name
title: Eli W. Hunter
subtitle: A quiet little corner of the Internet

# Social Media
github_url: https://github.com/elihunter173
linkedin_url: https://www.linkedin.com/in/elihunter173/
twitter_url: https://twitter.com/EliHunter173

# The subpath of your site, e.g. /blog
baseurl: ""
# The base hostname & protocol for your site, e.g. http://example.com
url: ""

# Front matter defaults
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/
  - Dockerfile
  - Session.vim
  - README.md
  - LICENSE
