# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site Variables
# These can be accessed such {{ site.foo }}. The site must restarted for these to be
# reloaded.
title: Paper Range
subtitle: A blog about a ~~narrow~~ range of things
name: Eli W. Hunter
resume:

# Social Media
github_url: https://github.com/elihunter173
linkedin_url: https://www.linkedin.com/in/elihunter173/
twitter_url: https://twitter.com/EliHunter173

# The subpath of your site, e.g. /blog
baseurl: "/paper-range"
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Front matter defaults
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Build settings
# Markdown and LaTeX setup
markdown: kramdown
kramdown:
  math_engine: mathjax

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
