version: '3'

services:
  nginx:
    build:
      context: ..
    restart: always
    volumes:
      - "./certbot/conf:/etc/letsencrypt"
      - "./certbot/www:/var/www/certbot"
    ports:
      - "80:80"
      - "443:443"
    # So we automatically reload our SSL certificates
    command: "/bin/sh -c 'while :; do sleep 6h; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    restart: always
    volumes:
      - "./certbot/conf:/etc/letsencrypt"
      - "./certbot/www:/var/www/certbot"
    # So certbot automatically tries to renew every 12h
    # Entrypoint because certbot defines entrypoint of 'certbot'
    entrypoint: "/bin/sh -c 'while :; do certbot renew; sleep 12h; done;'"
