on:
  push:
    branches: ["main"]

name: Build and deploy on push

env:
  RUST_CHANNEL: stable

jobs:
  build:
    name: Deploy website
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@main
      with:
        node-version: '16'

    - name: Install asteroids deps
      uses: actions/setup-node@v2

    - name: Install city-game deps
      run: |
        rustup update --no-self-update ${{ env.RUST_CHANNEL }}
        rustup default ${{ env.RUST_CHANNEL }}
        rustup target install wasm32-unknown-unknown
        cargo install wasm-bindgen-cli

    - name: Build website
      run: ./scripts/build.sh
      env:
        GITHUB_TOKEN: $GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}
