on: push
name: Build and deploy on push
jobs:
  build:
    # TODO: Minify everything
    name: shalzz/zola-deploy-action
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@master
      with:
        node-version: '16'

    - name: Install npm
      uses: actions/setup-node@v2

    - name: Build website
      run: ./scripts/build.sh
      env:
        GITHUB_TOKEN: $GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}
